### ISSUE TITLE
v0.0.2 run with fail

### ISSUE THREAD

**Issue by yarkovaleksei** [MitkoTschimev/jsdoc-webpack-plugin#11]
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn /mnt/Work/DM/frontend/node_modules/jsdoc-webpack-plugin/node_modules/.bin/jsdoc ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```
My JSDoc.conf
```javascript
{
    "tags": {
        "allowUnknownTags": true,
        "dictionaries": [ "jsdoc" ]
    },
    "templates": {
        "default": {
            "useLongnameInNav": true
        },
        "systemName": "",
        "analytics": {
            "ua": "",
            "domain": ""
        },
        "dateFormat": "dd-MM-YY hh:mm:ss",
        "theme": "spacelab",
        "syntaxTheme": "dark",
        "openGraph": {
            "title": "",
            "type": "website",
            "image": "",
            "site_name": "Documentation",
            "url": ""
        },
        "meta": {
            "title": "Documentation",
            "description": "",
            "keyword": ""
        },
        "outputSourceFiles": true,
        "outputSourcePath": true,
        "collapseSymbols": true,
        "linenums": true,
        "inverseNav": true,
        "cleverLinks": true,
        "monospaceLinks": false
    },
    "plugins": [
        "plugins/markdown",
        "plugins/summarize"
    ],
    "opts": {
        "template": "./node_modules/ink-docstrap/template",
        "encoding": "utf8",
        "destination": "./docs",
        "recurse": true,
        "source": {
            "includePattern": ".+\\.js(doc|x)?$"
        }
    }
}
```
Webpack 3 version.

**Comment by lmuresan** [comment]
I have the same problem. Has someone manage to fix it ?

**Comment by meibegger** [comment]
+1

**Comment by lmuresan** [comment]
I switch to esdoc and added the command as script in the package.json and it work perfectly.

**Comment by JarvisH** [comment]
I believe this has to do with the flat dependency structure in npm v3.

This line causes the error because no node_modules folder exists inside 'jsdoc-webpack-plugin'
`57: jsdoc = spawn(__dirname + '/node_modules/.bin/jsdoc', ['-c', jsDocConfTmp]);`

I tried changing it to the following which seems to resolve the error:
`jsdoc = spawn(path.resolve(cwd) + '/node_modules/.bin/jsdoc', ['-c', jsDocConfTmp]);`

**Comment by chrisdel101** [comment]
I have this problem too. I did not have a conf file before this. Added one with the defaults from Jsdocs docs and I get this error.

**Comment by MitkoTschimev** [comment]
Closing because of inactivity
