### ISSUE TITLE
Can't generate JSDoc

### ISSUE THREAD

**Issue by ninofiliu** [MitkoTschimev/jsdoc-webpack-plugin#15]
Guten Tag @MitkoTschimev and thanks for maintaining this plugin!

I am trying to add this plugin to my build pipeline but I'm running into an issue while trying to follow the README's instructions.

Code: [this minimal repo](https://github.com/ninofiliu/bug-reports/tree/master/jsdoc-webpack-plugin), basically a minimal webpack-built library

Expected behavior: `webpack` builds the library

Observed behavior: `webpack` fails when trying to generate JSDoc with the error log below

```
> greetings@0.0.0 build /home/nino/bug-reports/jsdoc-webpack-plugin
> webpack

(node:12469) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
JSDOC Start generating
/home/nino/bug-reports/jsdoc-webpack-plugin/node_modules/jsdoc-webpack-plugin/index.js:40
          chunk.modules.forEach(function (module) {
                        ^

TypeError: Cannot read property 'forEach' of undefined
    at /home/nino/bug-reports/jsdoc-webpack-plugin/node_modules/jsdoc-webpack-plugin/index.js:40:25
    at Array.forEach (<anonymous>)
    at /home/nino/bug-reports/jsdoc-webpack-plugin/node_modules/jsdoc-webpack-plugin/index.js:39:28
    at /home/nino/bug-reports/jsdoc-webpack-plugin/node_modules/jsonfile/index.js:46:5
    at /home/nino/bug-reports/jsdoc-webpack-plugin/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! greetings@0.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the greetings@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nino/.npm/_logs/2019-06-18T11_44_56_209Z-debug.log
```

**Comment by MitkoTschimev** [comment]
Hi @ninofiliu,

I wouldn't say maintaining the plugin about myself because I am just merging Pull Requests of people who make changes and checking if it looks good.

I would suggest asking the following people because they used it not long ago.

@ojathelonius and @maxhartshorn
