### ISSUE TITLE
Fails to generate docs

### ISSUE THREAD

**Issue by andreiblaji-cc** [MitkoTschimev/jsdoc-webpack-plugin#8]
Hi @tfiwm, first of all thank you for the such a great plugin, it's very helpful tool. I've recently started using it and run into an issue:

I'm using this plugin with webpack
I've installed latest version of the plugin : 0.0.2

Setup: 
created jsdoc.conf file
included plugin into webpack.config
in webpack config pointed plugin to jsdoc.conf file

when i run webpack it fails with following error:
```JSDOC Start generating
Taking sources from config file

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

Running jsdoc from terminal does not throw any error.
Tested with plugin v.0.0.1, and it works well, no error either.

**Comment by MitkoTschimev** [comment]
I will try to take a look as soon as possible ;)

**Comment by SwankyLegg** [comment]
I'm working on macOS. I had a similar error. Rolling back to the [previous commit](https://github.com/tfiwm/jsdoc-webpack-plugin/commit/10ad31a41ea0bbe076b41e55468681338b95d783) made it run. Still not working quite right, but it eliminated that error for me.

**Comment by leighlawhon** [comment]
I managed to fix it on my setup but don't have time to figure out which step fixed it. This is what I did in addition to the above:

1. Installed `jsdocs-babel` plugin (probably this fixed it?)
2. created `jsdoc.conf` file (below) and pointed to it in my Webpack plugin config (not shown)
```
{
  "plugins": ["node_modules/jsdoc-babel"],
  "babel": {
      "extensions": ["js", "es6", "jsx"]
  }
}
```
3. in my `package.json` I added a script for it and added it to my start config (Note, I am using concurrently plugin):

```
"scripts": {
  "docs": "jsdoc ./src",
  "start": "concurrently --kill-others  \"npm run docs && npm run startASCII\"  \"node server.js --env=dev\"",
  ...
}
```

**Comment by MitkoTschimev** [comment]
Closing because of inactivity and newer versions
