### ISSUE TITLE
Version 0.0.2 fails to generate docs

### ISSUE THREAD

**Issue by sikrip** [MitkoTschimev/jsdoc-webpack-plugin#9]
Version 0.0.2 fails to generate docs both in windows and linux environments. I tracked down the problem and found that the following lines

        if(/^win/.test(process.platform))
            jsdoc = spawn(__dirname + '/node_modules/.bin/jsdoc.cmd', ['-c', jsDocConfTmp]);
        else
            jsdoc = spawn(__dirname + '/node_modules/.bin/jsdoc', ['-c', jsDocConfTmp]);

need to change to 

        if(/^win/.test(process.platform))
            jsdoc = spawn(__dirname + '/../.bin/jsdoc.cmd', ['-c', jsDocConfTmp]);
        else
            jsdoc = spawn(__dirname + '/../.bin/jsdoc', ['-c', jsDocConfTmp]);

in order for the correct executable to be picked.

Could you please fix this problem?

**Comment by vagdwd** [comment]
Facing the same issue related to location of jsdoc binary.

**Comment by deryni** [comment]
The problem here seems to be caused by npm installing jsdoc into the toplevel/main `node_modules` directory and not in `jsdoc-webpack-plugin/node_modules`.

This happens when npm only needs to install one version of jsdoc (because nothing else uses it or everything agrees on a version). Forcibly installing an older (pre-3.4.0) version of jsdoc in the toplevel and then installing this module causes npm to create the expected `jsdoc-webpack-plugin/node_modules/jsdoc` directory and `jsdoc-webpack-plugin/node_modules/.bin/jsdoc` symlink and lets this work.

It seems to me like the plugin just needs to check for both possible paths... though better might be to be able to find out where npm put it in the first place (but `require` can't load it and I'm not sure how else to find it).

**Comment by jgrauel** [comment]
I made change similar to above, but just told the index `jsdoc = spawn(path.resolve(process.cwd(),'node_modules/jsdoc'), ['-c', jsDocConfTmp])`
however now I get a permission error:'internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
...'
Has anyone else encountered this? is it just because i am targeting up a level?
I will note that just adding a symbolic link to the root level install of jsdocs does work to get a complete run, but doesnt appear to be reading my config for the src location

**Comment by MitkoTschimev** [comment]
Closing because of inactivity and newer versions
